const provinceCodes = {
    "Álava": 1,
    "Albacete": 2,
    "Alicante": 3,
    "Almería": 4,
    "Asturias": 33,
    "Ávila": 5,
    "Badajoz": 6,
    "Barcelona": 8,
    "Burgos": 9,
    "Cáceres": 10,
    "Cádiz": 11,
    "Cantabria": 39,
    "Castellón": 12,
    "Ciudad Real": 13,
    "Córdoba": 14,
    "Cuenca": 16,
    "Gerona": 17,
    "Granada": 18,
    "Guadalajara": 19,
    "Gipuzkoa": 20,
    "Huelva": 21,
    "Huesca": 22,
    "Islas Baleares": 7,
    "Jaén": 23,
    "La Rioja": 26,
    "Las Palmas": 35,
    "León": 24,
    "Lleida": 25,
    "Madrid": 28,
    "Málaga": 29,
    "Murcia": 30,
    "Navarra": 31,
    "Ourense": 32,
    "Palencia": 34,
    "Pontevedra": 36,
    "Salamanca": 37,
    "Segovia": 40,
    "Sevilla": 41,
    "Soria": 42,
    "Tarragona": 43,
    "Teruel": 44,
    "Toledo": 45,
    "Valencia": 46,
    "Valladolid": 47,
    "Vizcaya": 48,
    "Zamora": 49,
    "Zaragoza": 50
  };
  
  export default provinceCodes;
  